---
title: "P2"
author: "Henoc Codjie"
date: "2023-03-28"
output: html_document
---

```{r}

library(readr)
library(dplyr)
library(corrplot)
library(ggplot2)
library(caret)
library(car)
library(corrplot)
library(leaps)

source("https://raw.githubusercontent.com/JA-McLean/STOR455/master/scripts/ShowSubsets.R")
```


```{r}

data1 <- read_csv("Final_Data.csv")

head(data1)


colnames(data1)[2] ="Home_ID"

colnames(data1)[3] ="Away_ID"

data1$Total = data1$Home_pts + data1$Away_pts

data1$Oreb = data1$Home_oreb + data1$Away_oreb

data1

```

```{r}

df <- subset(data1, select = -c(...1,Day,Home_pts,Away_pts,Spread,Home_oreb,Away_oreb,Home_FGPct,Away_FGPct,Home_3Pct,Away_3Pct,Home_Steals,Away_Steals,Left_pts,Right_pts,Left_FGPct,Right_FGPct,Left_oreb,Right_oreb,Left_3Pct,Right_3Pct,Total))


df

df2 <- subset(data1, select = -c(...1,Day,Home_pts,Away_pts,Spread,Home_oreb,Away_oreb,Home_FGPct,Away_FGPct,Home_3Pct,Away_3Pct,Home_Steals,Away_Steals,Left_pts,Right_pts,Left_FGPct,Right_FGPct,Left_oreb,Right_oreb,Left_3Pct,Right_3Pct,Oreb))


df2

df3 <- subset(data1, select = -c(...1,Day,Home_pts,Away_pts,Home_oreb,Away_oreb,Home_FGPct,Away_FGPct,Home_3Pct,Away_3Pct,Home_Steals,Away_Steals,Left_pts,Right_pts,Left_FGPct,Right_FGPct,Left_oreb,Right_oreb,Left_3Pct,Right_3Pct,Oreb))


df3


```


```{r}

set.seed(69)


trainIndex <- createDataPartition(df$Oreb, p = .8, list = FALSE)

train <- df[trainIndex, ]

test <- df[-trainIndex, ]



```

```{r}

# Fit the full model
Full = lm(Oreb~., data = train)

# Find the MSE for the full model
MSE=(summary(Full)$sigma)^2

# Start with a model with NO predictors
none = lm(Oreb~1, data=train)

# Don’t specify a direction
step(none,scope=list(upper=Full),scale=MSE)

```

```{r}

model1 <- lm(formula = Oreb ~ Left_PPG, data = train)

predictions1 <- predict(model1, newdata = test)

rmse1 <- sqrt(mean((predictions1 - test$Oreb) ^ 2))

rmse1

```

```{r}


knn_model <- train(Oreb ~ ., data = train, method = "knn", trControl = trainControl(method = "cv", number = 5), preProcess = c("center", "scale"), tuneLength = 10, metric = "RMSE", na.action=na.exclude)


```

```{r}

predictions2 <- predict(knn_model, newdata = test)

rmse2 <- sqrt(mean((predictions2 - test$Oreb) ^ 2))

rmse2

```


```{r}

# Fit the full model
Full = lm(Oreb~(Home_ID+Away_ID+Game_id+ Spread_Pred+Home_TPG+Away_TPG+Home_TSG+Away_TSG+Home_TOG+Away_TOG+Home_PPG+Away_PPG+Home_SPG+Away_SPG+Home_OPG+Away_OPG+Matchup_ID+Left_ID+Right_ID+Left_TPG+Right_TPG+Left_TSG+Right_TSG+Left_TOG+Right_TOG+Left_PPG+Right_PPG+Left_SPG+Right_SPG+Left_OPG+Right_TSG+Left_TOG+Right_TOG+Left_PPG+Right_PPG+Left_SPG+Right_SPG+Left_OPG+Right_OPG)^2, data = na.omit(train))

# Find the MSE for the full model
MSE=(summary(Full)$sigma)^2

# Start with a model with NO predictors
none = lm(Oreb~1, data=train)

# Don’t specify a direction
step(none,scope=list(upper=Full),scale=MSE)



```

```{r}

all = regsubsets(Oreb~(Home_ID+Away_ID+Game_id+ Spread_Pred+Home_TPG+Away_TPG+Home_TSG+Away_TSG+Home_TOG+Away_TOG+Home_PPG+Away_PPG+Home_SPG+Away_SPG+Home_OPG+Away_OPG+Matchup_ID+Left_ID+Right_ID+Left_TPG+Right_TPG+Left_TSG+Right_TSG+Left_TOG+Right_TOG+Left_PPG+Right_PPG+Left_SPG+Right_SPG+Left_OPG+Right_TSG+Left_TOG+Right_TOG+Left_PPG+Right_PPG+Left_SPG+Right_SPG+Left_OPG+Right_OPG), data = na.omit(train))

summary(all)


```

```{r}

ShowSubsets(all)

```

```{r}

trainIndex2 <- createDataPartition(df2$Total, p = .8, list = FALSE)

train2 <- df2[trainIndex2, ]

test2 <- df2[-trainIndex2, ]


trainIndex3 <- createDataPartition(df3$Spread, p = .8, list = FALSE)

train3 <- df3[trainIndex3, ]

test3 <- df3[-trainIndex3, ]



```

```{r}


knn_model2 <- train(Total ~ ., data = train2, method = "knn", trControl = trainControl(method = "cv", number = 5), preProcess = c("center", "scale"), tuneLength = 10, metric = "RMSE", na.action=na.exclude)


```

```{r}

predictions3 <- predict(knn_model2, newdata = test2)

rmse3 <- sqrt(mean((predictions3 - test2$Total) ^ 2))

rmse3

```
```{r}


knn_model3 <- train(Spread ~ ., data = train3, method = "knn", trControl = trainControl(method = "cv", number = 5), preProcess = c("center", "scale"), tuneLength = 10, metric = "RMSE", na.action=na.exclude)


```

```{r}

predictions4 <- predict(knn_model3, newdata = test3)

rmse4 <- sqrt(mean((predictions3 - test3$Spread) ^ 2))

rmse4

```
```{r}

all2 = regsubsets(Total~(Home_ID+Away_ID+Game_id+ Spread_Pred+Home_TPG+Away_TPG+Home_TSG+Away_TSG+Home_TOG+Away_TOG+Home_PPG+Away_PPG+Home_SPG+Away_SPG+Home_OPG+Away_OPG+Matchup_ID+Left_ID+Right_ID+Left_TPG+Right_TPG+Left_TSG+Right_TSG+Left_TOG+Right_TOG+Left_PPG+Right_PPG+Left_SPG+Right_SPG+Left_OPG+Right_TSG+Left_TOG+Right_TOG+Left_PPG+Right_PPG+Left_SPG+Right_SPG+Left_OPG+Right_OPG), data = na.omit(train2))

summary(all2)


```

```{r}

ShowSubsets(all2)

```

```{r}

all3 = regsubsets(Total~(Home_ID+Away_ID+Game_id+ Spread_Pred+Home_TPG+Away_TPG+Home_TSG+Away_TSG+Home_TOG+Away_TOG+Home_PPG+Away_PPG+Home_SPG+Away_SPG+Home_OPG+Away_OPG+Matchup_ID+Left_ID+Right_ID+Left_TPG+Right_TPG+Left_TSG+Right_TSG+Left_TOG+Right_TOG+Left_PPG+Right_PPG+Left_SPG+Right_SPG+Left_OPG+Right_TSG+Left_TOG+Right_TOG+Left_PPG+Right_PPG+Left_SPG+Right_SPG+Left_OPG+Right_OPG), data = na.omit(train3))

summary(all3)


```

```{r}

ShowSubsets(all3)

```

```{r}

train3 <- na.omit(train3)

# Fit the full model
Full = lm(Spread~., data = train3)

# Find the MSE for the full model
MSE=(summary(Full)$sigma)^2

# Start with a model with NO predictors
none = lm(Spread~1, data=train3)

# Don’t specify a direction
step(none,scope=list(upper=Full),scale=MSE)


```

```{r}

train3 <- na.omit(train3)

test3 <- na.omit(test3)

model <- lm(formula = Spread ~ Spread_Pred, data = train3)

predictions <- predict(model, newdata = test3)

rmse <- sqrt(mean((test3$Spread - predictions) ^ 2))

rmse

summary(model)
```

```{r}

# Fit the full model
Full = lm(Spread~poly(Home_ID+Away_ID+Game_id+ Spread_Pred+Home_TPG+Away_TPG+Home_TSG+Away_TSG+Home_TOG+Away_TOG+Home_PPG+Away_PPG+Home_SPG+Away_SPG+Home_OPG+Away_OPG), data = na.omit(train3))

# Find the MSE for the full model
MSE=(summary(Full)$sigma)^2

# Start with a model with NO predictors
none = lm(Spread~1, data=train3)

# Don’t specify a direction
step(none,scope=list(upper=Full),scale=MSE)

```

```{r}


train3 <- na.omit(train3)

test3 <- na.omit(test3)

model <- lm(formula = Spread ~ 1, data = train3)

predictions <- predict(model, newdata = test3)

rmse <- sqrt(mean((test3$Spread - predictions) ^ 2))

rmse

summary(model)

```

